### ISSUE TITLE
[FEATURE]: More info on failed/skipped applications

### ISSUE THREAD

**Issue by javad3zafar** [AIHawk-co/Auto_Jobs_Applier_AI_Agent#755]
### Feature summary

Add 'reason' in failed and skipped json

### Feature description

We have two JSON files that list the failed and skipped job applications where the bot either failed to apply or chose to skip for some reason. The "reason" in these files provides valuable information that can help improve our bot settings or resume tuning, enhancing our chances of securing better job matches.

### Motivation

Improve our bot settings or resume tuning

### Alternatives considered

add reason to skipped.json and failed.json

**Comment by cjbbb** [comment]
Usually, skip because "ai suitable score" or "black title list". Your issues are great and I will work on it.

**Comment by javad3zafar** [comment]
> ai suitable score

What does "AI suitability score" mean?

Also, I don’t have any blacklist for job titles, companies, or countries. One thing I noticed in both files is that the "job_recruiter" field is empty: "job_recruiter": "". I didn’t check that part of the code, so I’m not sure if this is a bug. However, it’s possible that if a job offer has no recruiter listed, the bot might decide to skip it for no valid reason.

If any help is needed, I’d be glad to assist.

**Comment by cjbbb** [comment]
> > ai suitable score
> 
> What does "AI suitability score" mean?
> 
> Also, I don’t have any blacklist for job titles, companies, or countries. One thing I noticed in both files is that the "job_recruiter" field is empty: "job_recruiter": "". I didn’t check that part of the code, so I’m not sure if this is a bug. However, it’s possible that if a job offer has no recruiter listed, the bot might decide to skip it for no valid reason.
> 
> If any help is needed, I’d be glad to assist.

the reason part was added as #765. As for case  "job_recruiter": "", I will test it and check.

If you find other bugs, you can just create a PR and @ me to review. Thx for your help!

**Comment by cjbbb** [comment]
Merged with release/11.15 and will merge with main branch. Close
