### ISSUE TITLE
[BUG]: Generate two logging files

### ISSUE THREAD

**Issue by cjbbb** [AIHawk-co/Auto_Jobs_Applier_AI_Agent#778]
### Describe the bug

Logging backups, log rotation entire broke, no more log zip files are getting generated.
I caused it due to generating different log files for each run.

### Steps to reproduce

on "release 11.15" branch

Try running multiple files

### Expected behavior
Logger module should work expected - log rotation, log compression & log retention.

Also has bug fix for https://github.com/AIHawk-co/Auto_Jobs_Applier/issues/762
Separating selenium logs fixing concurrency issues.

**Comment by cjbbb** [comment]
oaky app.log is chrome log

**Comment by surapuramakhil** [comment]
@feder-cr impact of last hack, which we merged into main.

@cjbbb I am not sure what you are trying to achieve. Bug says logs are going two log files, Expected is only write in one log file.

this PR https://github.com/AIHawk-co/Auto_Jobs_Applier/pull/779 still generates two log files just the thing is none of these named as app.log.

**Comment by surapuramakhil** [comment]
@cjbbb can you do tree log folder.

**Comment by surapuramakhil** [comment]
@cjbbb thanks for jumping on discord & clarifying the issue.

**Comment by cjbbb** [comment]
Merged
